algoritmo "fichaRPG"
// criar uma ficha de RPG com nome e dade do player seguido de nome, idade, sexo, fobia, habilidade, progenitor divino, classe e arma e ela precisa ser responsiva ao final.

var 
nomePlayer, nomeChar, sexo, fobia, habilidade, progdiv, class, arma, titulo: caractere
var
idadePlayer, idadeChar: inteiro 
inicio
  escreval ("▬▬▬▬▬▬▬▬")
  escreval ("◱⃟✿New Saogalemu◲⃟✿")
  escreval ("▬▬▬▬▬▬▬▬")
  escreval ( "Bem vindo, por favor responda as seguintes questões")
  escreval ("Qual é o seu nome/pseudo?" )
  leia (nomePlayer)
  escreval ("Qual é a sua Idade:")
  leia (idadePlayer)
  escreval ("𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿")
  escreval ("Agora vamos ao que interessa, por favor responda as questões a seguir da forma que deseja seu char (personagem)")
  escreval ("𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿")
  escreval (" 𓁞  .⃟𔒿 Dados do Personagem 𔒿⃟.  𓁛")
  escreval ("𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿")
  escreval ("Nome do personagem: ")
  leia (nomeChar)
  escreval ("𔒿𔒿𔒿𔒿𔒿𔒿")
  escreval ("Idade:")
  leia (idadeChar)
  escreval ("𔒿𔒿𔒿𔒿𔒿𔒿")
  escreval ("Sexo:")
  leia (sexo)
  escreval ("𔒿𔒿𔒿𔒿𔒿𔒿")
  escreval ("Fobia:")
  leia (fobia)
  escreval ("𔒿𔒿𔒿𔒿𔒿𔒿")
  escreval ("Habilidade (máximo 2):")
  leia (habilidade)
  escreval ("𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿")
  escreval (" De qual Progenitor Divino ele descende:")
  leia (progdiv)
  escreval ("𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿")
  escreval ("Qual o Título do seu char (personagem):")
  leia (titulo)
  escreval ("𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿")
  escreval ("Qual Arma deseja usar (uma arma apenas):")
  leia (arma)
  
  escreval("")
  escreval ("𐜤⃟𐇽𐍹๛▸Dadod do Player:")
  escreval ("𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿")
  escreval ("𐜤⃟𐇽𐍹๛▸Nome:", nomePlayer)
  escreval (" ﹌﹋")
  escreval ("𐜤⃟𐇽𐍹๛▸Idade:", idadePlayer)
  escreval ("𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿")
  escreval (" 𓁞  .⃟𔒿 Dados do Personagem 𔒿⃟.  𓁛")
  escreval ("𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿𔒿")
  escreval ("Nome: ", nomeChar)
  escreval ("𔒿𔒿𔒿𔒿𔒿𔒿")
  escreval ("Idade:", idadeChar)
  escreval ("𔒿𔒿𔒿𔒿𔒿𔒿")
  escreval ("Sexo:", sexo)
  escreval ("𔒿𔒿𔒿𔒿𔒿𔒿")
  escreval ("Fobia:", fobia)
  escreval ("𔒿𔒿𔒿𔒿𔒿𔒿")
  escreval ("Habilidade (máximo 2):", habilidade)
  escreval ("𔒿𔒿𔒿𔒿𔒿𔒿")
  escreval ("Progenitor Divino:", progdiv)
  escreval ("𔒿𔒿𔒿𔒿𔒿𔒿")
  escreval ("Título:", titulo)
  escreval ("𔒿𔒿𔒿𔒿𔒿𔒿")
  escreval ("Arma (uma arma apenas):", arma)
  escreval ("𔒿𔒿𔒿𔒿𔒿𔒿")
fimalgoritmo
